// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import ContentIndex from './ContentIndex/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	biography: Biography,
	content_index: ContentIndex,
	experience: Experience,
	hero: Hero,
	rich_text: RichText,
	tech_list: TechList
};
